#!/usr/bin/env python3
"""Export content/ JSON files → data.js for website"""
import json, os

BASE = os.path.dirname(__file__) + '/..'

# Load all content
photos = json.load(open(f'{BASE}/content/photos/index.json'))
series = json.load(open(f'{BASE}/content/series/index.json'))

# Build sections from series photos
sections = {}
with open(f'{BASE}/src/data/site.json') as f:
    site = json.load(f)
    sections = site.get('sections', {})

# Assemble SITE_DATA
data = {
    'photos': photos,
    'sections': sections
}

# Write data.js
js = '// Generated by content pipeline\nconst SITE_DATA = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';'
with open(f'{BASE}/data.js', 'w') as f:
    f.write(js)

# Write data.json backup
with open(f'{BASE}/data.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Update series.js
series_js = '// Generated by content pipeline\nconst SERIES_DATA = ' + json.dumps(series, ensure_ascii=False, indent=2) + ';'
with open(f'{BASE}/src/data/series.js', 'w') as f:
    f.write(series_js)

print(f'✅ data.js + series.js generated ({len(photos)} photos, {len(series)} series)')
